# Generated by Django 4.0.3 on 2022-03-04 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomM', models.CharField(max_length=20)),
                ('PrenomM', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateR', models.DateField(null=True)),
                ('HeureR', models.TimeField()),
                ('ButR', models.CharField(max_length=200)),
                ('DecisionR', models.CharField(max_length=200)),
                ('TacheR', models.CharField(max_length=200)),
                ('id_Membre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pv_maker.membre')),
            ],
        ),
        migrations.CreateModel(
            name='Avoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Membre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pv_maker.membre')),
                ('id_Reunion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pv_maker.reunion')),
            ],
        ),
    ]
